# Generated by Django 5.0.5 on 2024-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="created_on",
        ),
    ]
